In [33]:
import pandas as pd


df1 = pd.read_csv("data/per1.csv")
df2 = pd.read_csv("data/per2.csv")

In [34]:
df = df1.merge(df2, how="outer")

In [35]:
df.to_csv("data/per.csv")

In [13]:
df1

,Relative Time (Process),default-8-b - _step,default-8-b - _step__MIN,default-8-b - _step__MAX,default-8-b - Visited Rooms,default-8-b - Visited Rooms__MIN,default-8-b - Visited Rooms__MAX,default-8-c - _step,default-8-c - _step__MIN,default-8-c - _step__MAX,...,default-1-a - _step__MAX,default-1-a - Visited Rooms,default-1-a - Visited Rooms__MIN,default-1-a - Visited Rooms__MAX,default-1-b - _step,default-1-b - _step__MIN,default-1-b - _step__MAX,default-1-b - Visited Rooms,default-1-b - Visited Rooms__MIN,default-1-b - Visited Rooms__MAX
0,11,0.0,0.0,0.0,1.0,1.0,1.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,18,1.0,1.0,1.0,1.0,1.0,1.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1.0,1.0,1.0,1.0,1.0,1.0
3,21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,25,2.0,2.0,2.0,1.0,1.0,1.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94459,527654,NaN,NaN,NaN,NaN,NaN,NaN,152652.0,152652.0,152652.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
94460,527665,NaN,NaN,NaN,NaN,NaN,NaN,152655.0,152655.0,152655.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
94461,527723,NaN,NaN,NaN,NaN,NaN,NaN,152672.0,152672.0,152672.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
94462,527734,NaN,NaN,NaN,NaN,NaN,NaN,152675.0,152675.0,152675.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
94463,527741,NaN,NaN,NaN,NaN,NaN,NaN,152677.0,152677.0,152677.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
df2

,Relative Time (Process),default-1-f - _step,default-1-f - _step__MIN,default-1-f - _step__MAX,default-1-f - Visited Rooms,default-1-f - Visited Rooms__MIN,default-1-f - Visited Rooms__MAX,default-1-e - _step,default-1-e - _step__MIN,default-1-e - _step__MAX,...,default-6-c - _step__MAX,default-6-c - Visited Rooms,default-6-c - Visited Rooms__MIN,default-6-c - Visited Rooms__MAX,default-8-a - _step,default-8-a - _step__MIN,default-8-a - _step__MAX,default-8-a - Visited Rooms,default-8-a - Visited Rooms__MIN,default-8-a - Visited Rooms__MAX
0,14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN
1,18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,35,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,3.0,3.0,3.0,1.0,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
92020,599629,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
92021,599673,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
92022,599698,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
92023,599719,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
92024,599806,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
df

,Relative Time (Process),default-8-b - _step,default-8-b - _step__MIN,default-8-b - _step__MAX,default-8-b - Visited Rooms,default-8-b - Visited Rooms__MIN,default-8-b - Visited Rooms__MAX,default-8-c - _step,default-8-c - _step__MIN,default-8-c - _step__MAX,...,default-6-c - _step__MAX,default-6-c - Visited Rooms,default-6-c - Visited Rooms__MIN,default-6-c - Visited Rooms__MAX,default-8-a - _step,default-8-a - _step__MIN,default-8-a - _step__MAX,default-8-a - Visited Rooms,default-8-a - Visited Rooms__MIN,default-8-a - Visited Rooms__MAX
0,11,0.0,0.0,0.0,1.0,1.0,1.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,18,1.0,1.0,1.0,1.0,1.0,1.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,25,2.0,2.0,2.0,1.0,1.0,1.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
167540,599629,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
167541,599673,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
167542,599698,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
167543,599719,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
167544,599806,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN